/* eslint-disable */
/* tslint:disable */
/* auto-generated react proxies */
import { createReactComponent } from './react-component-lib';

import type { JSX } from '@tarojs/components/dist/components';

import { defineCustomElement as defineTaroAdCore } from '@tarojs/components/dist/components/taro-ad-core.js';
import { defineCustomElement as defineTaroAdCustomCore } from '@tarojs/components/dist/components/taro-ad-custom-core.js';
import { defineCustomElement as defineTaroAnimationVideoCore } from '@tarojs/components/dist/components/taro-animation-video-core.js';
import { defineCustomElement as defineTaroAnimationViewCore } from '@tarojs/components/dist/components/taro-animation-view-core.js';
import { defineCustomElement as defineTaroArCameraCore } from '@tarojs/components/dist/components/taro-ar-camera-core.js';
import { defineCustomElement as defineTaroAudioCore } from '@tarojs/components/dist/components/taro-audio-core.js';
import { defineCustomElement as defineTaroAwemeDataCore } from '@tarojs/components/dist/components/taro-aweme-data-core.js';
import { defineCustomElement as defineTaroBlockCore } from '@tarojs/components/dist/components/taro-block-core.js';
import { defineCustomElement as defineTaroButtonCore } from '@tarojs/components/dist/components/taro-button-core.js';
import { defineCustomElement as defineTaroCameraCore } from '@tarojs/components/dist/components/taro-camera-core.js';
import { defineCustomElement as defineTaroCanvasCore } from '@tarojs/components/dist/components/taro-canvas-core.js';
import { defineCustomElement as defineTaroChannelLiveCore } from '@tarojs/components/dist/components/taro-channel-live-core.js';
import { defineCustomElement as defineTaroChannelVideoCore } from '@tarojs/components/dist/components/taro-channel-video-core.js';
import { defineCustomElement as defineTaroCheckboxCore } from '@tarojs/components/dist/components/taro-checkbox-core.js';
import { defineCustomElement as defineTaroCheckboxGroupCore } from '@tarojs/components/dist/components/taro-checkbox-group-core.js';
import { defineCustomElement as defineTaroCommentDetailCore } from '@tarojs/components/dist/components/taro-comment-detail-core.js';
import { defineCustomElement as defineTaroCommentListCore } from '@tarojs/components/dist/components/taro-comment-list-core.js';
import { defineCustomElement as defineTaroContactButtonCore } from '@tarojs/components/dist/components/taro-contact-button-core.js';
import { defineCustomElement as defineTaroCoverImageCore } from '@tarojs/components/dist/components/taro-cover-image-core.js';
import { defineCustomElement as defineTaroCoverViewCore } from '@tarojs/components/dist/components/taro-cover-view-core.js';
import { defineCustomElement as defineTaroCustomWrapperCore } from '@tarojs/components/dist/components/taro-custom-wrapper-core.js';
import { defineCustomElement as defineTaroDoubleTapGestureHandlerCore } from '@tarojs/components/dist/components/taro-double-tap-gesture-handler-core.js';
import { defineCustomElement as defineTaroDraggableSheetCore } from '@tarojs/components/dist/components/taro-draggable-sheet-core.js';
import { defineCustomElement as defineTaroEditorCore } from '@tarojs/components/dist/components/taro-editor-core.js';
import { defineCustomElement as defineTaroFollowSwanCore } from '@tarojs/components/dist/components/taro-follow-swan-core.js';
import { defineCustomElement as defineTaroForcePressGestureHandlerCore } from '@tarojs/components/dist/components/taro-force-press-gesture-handler-core.js';
import { defineCustomElement as defineTaroFormCore } from '@tarojs/components/dist/components/taro-form-core.js';
import { defineCustomElement as defineTaroFunctionalPageNavigatorCore } from '@tarojs/components/dist/components/taro-functional-page-navigator-core.js';
import { defineCustomElement as defineTaroGridBuilderCore } from '@tarojs/components/dist/components/taro-grid-builder-core.js';
import { defineCustomElement as defineTaroGridViewCore } from '@tarojs/components/dist/components/taro-grid-view-core.js';
import { defineCustomElement as defineTaroHorizontalDragGestureHandlerCore } from '@tarojs/components/dist/components/taro-horizontal-drag-gesture-handler-core.js';
import { defineCustomElement as defineTaroIconCore } from '@tarojs/components/dist/components/taro-icon-core.js';
import { defineCustomElement as defineTaroImageCore } from '@tarojs/components/dist/components/taro-image-core.js';
import { defineCustomElement as defineTaroInlinePaymentPanelCore } from '@tarojs/components/dist/components/taro-inline-payment-panel-core.js';
import { defineCustomElement as defineTaroInputCore } from '@tarojs/components/dist/components/taro-input-core.js';
import { defineCustomElement as defineTaroKeyboardAccessoryCore } from '@tarojs/components/dist/components/taro-keyboard-accessory-core.js';
import { defineCustomElement as defineTaroLabelCore } from '@tarojs/components/dist/components/taro-label-core.js';
import { defineCustomElement as defineTaroLifestyleCore } from '@tarojs/components/dist/components/taro-lifestyle-core.js';
import { defineCustomElement as defineTaroLikeCore } from '@tarojs/components/dist/components/taro-like-core.js';
import { defineCustomElement as defineTaroListBuilderCore } from '@tarojs/components/dist/components/taro-list-builder-core.js';
import { defineCustomElement as defineTaroListViewCore } from '@tarojs/components/dist/components/taro-list-view-core.js';
import { defineCustomElement as defineTaroLivePlayerCore } from '@tarojs/components/dist/components/taro-live-player-core.js';
import { defineCustomElement as defineTaroLivePusherCore } from '@tarojs/components/dist/components/taro-live-pusher-core.js';
import { defineCustomElement as defineTaroLoginCore } from '@tarojs/components/dist/components/taro-login-core.js';
import { defineCustomElement as defineTaroLongPressGestureHandlerCore } from '@tarojs/components/dist/components/taro-long-press-gesture-handler-core.js';
import { defineCustomElement as defineTaroLottieCore } from '@tarojs/components/dist/components/taro-lottie-core.js';
import { defineCustomElement as defineTaroMapCore } from '@tarojs/components/dist/components/taro-map-core.js';
import { defineCustomElement as defineTaroMatchMediaCore } from '@tarojs/components/dist/components/taro-match-media-core.js';
import { defineCustomElement as defineTaroMovableAreaCore } from '@tarojs/components/dist/components/taro-movable-area-core.js';
import { defineCustomElement as defineTaroMovableViewCore } from '@tarojs/components/dist/components/taro-movable-view-core.js';
import { defineCustomElement as defineTaroNativeSlotCore } from '@tarojs/components/dist/components/taro-native-slot-core.js';
import { defineCustomElement as defineTaroNavigationBarCore } from '@tarojs/components/dist/components/taro-navigation-bar-core.js';
import { defineCustomElement as defineTaroNavigatorCore } from '@tarojs/components/dist/components/taro-navigator-core.js';
import { defineCustomElement as defineTaroNestedScrollBodyCore } from '@tarojs/components/dist/components/taro-nested-scroll-body-core.js';
import { defineCustomElement as defineTaroNestedScrollHeaderCore } from '@tarojs/components/dist/components/taro-nested-scroll-header-core.js';
import { defineCustomElement as defineTaroOfficialAccountCore } from '@tarojs/components/dist/components/taro-official-account-core.js';
import { defineCustomElement as defineTaroOpenContainerCore } from '@tarojs/components/dist/components/taro-open-container-core.js';
import { defineCustomElement as defineTaroOpenDataCore } from '@tarojs/components/dist/components/taro-open-data-core.js';
import { defineCustomElement as defineTaroOpenEmbeddedAtomicserviceCore } from '@tarojs/components/dist/components/taro-open-embedded-atomicservice-core.js';
import { defineCustomElement as defineTaroPageContainerCore } from '@tarojs/components/dist/components/taro-page-container-core.js';
import { defineCustomElement as defineTaroPageMetaCore } from '@tarojs/components/dist/components/taro-page-meta-core.js';
import { defineCustomElement as defineTaroPanGestureHandlerCore } from '@tarojs/components/dist/components/taro-pan-gesture-handler-core.js';
import { defineCustomElement as defineTaroPickerCore } from '@tarojs/components/dist/components/taro-picker-core.js';
import { defineCustomElement as defineTaroPickerGroup } from '@tarojs/components/dist/components/taro-picker-group.js';
import { defineCustomElement as defineTaroPickerViewColumnCore } from '@tarojs/components/dist/components/taro-picker-view-column-core.js';
import { defineCustomElement as defineTaroPickerViewCore } from '@tarojs/components/dist/components/taro-picker-view-core.js';
import { defineCustomElement as defineTaroProgressCore } from '@tarojs/components/dist/components/taro-progress-core.js';
import { defineCustomElement as defineTaroPullToRefreshCore } from '@tarojs/components/dist/components/taro-pull-to-refresh-core.js';
import { defineCustomElement as defineTaroRadioCore } from '@tarojs/components/dist/components/taro-radio-core.js';
import { defineCustomElement as defineTaroRadioGroupCore } from '@tarojs/components/dist/components/taro-radio-group-core.js';
import { defineCustomElement as defineTaroRichTextCore } from '@tarojs/components/dist/components/taro-rich-text-core.js';
import { defineCustomElement as defineTaroRootPortalCore } from '@tarojs/components/dist/components/taro-root-portal-core.js';
import { defineCustomElement as defineTaroRtcRoomCore } from '@tarojs/components/dist/components/taro-rtc-room-core.js';
import { defineCustomElement as defineTaroRtcRoomItemCore } from '@tarojs/components/dist/components/taro-rtc-room-item-core.js';
import { defineCustomElement as defineTaroScaleGestureHandlerCore } from '@tarojs/components/dist/components/taro-scale-gesture-handler-core.js';
import { defineCustomElement as defineTaroScriptCore } from '@tarojs/components/dist/components/taro-script-core.js';
import { defineCustomElement as defineTaroScrollViewCore } from '@tarojs/components/dist/components/taro-scroll-view-core.js';
import { defineCustomElement as defineTaroShareElementCore } from '@tarojs/components/dist/components/taro-share-element-core.js';
import { defineCustomElement as defineTaroSliderCore } from '@tarojs/components/dist/components/taro-slider-core.js';
import { defineCustomElement as defineTaroSlotCore } from '@tarojs/components/dist/components/taro-slot-core.js';
import { defineCustomElement as defineTaroSnapshotCore } from '@tarojs/components/dist/components/taro-snapshot-core.js';
import { defineCustomElement as defineTaroSpanCore } from '@tarojs/components/dist/components/taro-span-core.js';
import { defineCustomElement as defineTaroStickyHeaderCore } from '@tarojs/components/dist/components/taro-sticky-header-core.js';
import { defineCustomElement as defineTaroStickySectionCore } from '@tarojs/components/dist/components/taro-sticky-section-core.js';
import { defineCustomElement as defineTaroSwiperCore } from '@tarojs/components/dist/components/taro-swiper-core.js';
import { defineCustomElement as defineTaroSwiperItemCore } from '@tarojs/components/dist/components/taro-swiper-item-core.js';
import { defineCustomElement as defineTaroSwitchCore } from '@tarojs/components/dist/components/taro-switch-core.js';
import { defineCustomElement as defineTaroTabItemCore } from '@tarojs/components/dist/components/taro-tab-item-core.js';
import { defineCustomElement as defineTaroTabbar } from '@tarojs/components/dist/components/taro-tabbar.js';
import { defineCustomElement as defineTaroTabsCore } from '@tarojs/components/dist/components/taro-tabs-core.js';
import { defineCustomElement as defineTaroTapGestureHandlerCore } from '@tarojs/components/dist/components/taro-tap-gesture-handler-core.js';
import { defineCustomElement as defineTaroTextCore } from '@tarojs/components/dist/components/taro-text-core.js';
import { defineCustomElement as defineTaroTextareaCore } from '@tarojs/components/dist/components/taro-textarea-core.js';
import { defineCustomElement as defineTaroVerticalDragGestureHandlerCore } from '@tarojs/components/dist/components/taro-vertical-drag-gesture-handler-core.js';
import { defineCustomElement as defineTaroVideoControl } from '@tarojs/components/dist/components/taro-video-control.js';
import { defineCustomElement as defineTaroVideoCore } from '@tarojs/components/dist/components/taro-video-core.js';
import { defineCustomElement as defineTaroVideoDanmu } from '@tarojs/components/dist/components/taro-video-danmu.js';
import { defineCustomElement as defineTaroViewCore } from '@tarojs/components/dist/components/taro-view-core.js';
import { defineCustomElement as defineTaroVoipRoomCore } from '@tarojs/components/dist/components/taro-voip-room-core.js';
import { defineCustomElement as defineTaroWebViewCore } from '@tarojs/components/dist/components/taro-web-view-core.js';

export const TaroAdCore = /*@__PURE__*/createReactComponent<JSX.TaroAdCore, HTMLTaroAdCoreElement>('taro-ad-core', undefined, undefined, defineTaroAdCore);
export const TaroAdCustomCore = /*@__PURE__*/createReactComponent<JSX.TaroAdCustomCore, HTMLTaroAdCustomCoreElement>('taro-ad-custom-core', undefined, undefined, defineTaroAdCustomCore);
export const TaroAnimationVideoCore = /*@__PURE__*/createReactComponent<JSX.TaroAnimationVideoCore, HTMLTaroAnimationVideoCoreElement>('taro-animation-video-core', undefined, undefined, defineTaroAnimationVideoCore);
export const TaroAnimationViewCore = /*@__PURE__*/createReactComponent<JSX.TaroAnimationViewCore, HTMLTaroAnimationViewCoreElement>('taro-animation-view-core', undefined, undefined, defineTaroAnimationViewCore);
export const TaroArCameraCore = /*@__PURE__*/createReactComponent<JSX.TaroArCameraCore, HTMLTaroArCameraCoreElement>('taro-ar-camera-core', undefined, undefined, defineTaroArCameraCore);
export const TaroAudioCore = /*@__PURE__*/createReactComponent<JSX.TaroAudioCore, HTMLTaroAudioCoreElement>('taro-audio-core', undefined, undefined, defineTaroAudioCore);
export const TaroAwemeDataCore = /*@__PURE__*/createReactComponent<JSX.TaroAwemeDataCore, HTMLTaroAwemeDataCoreElement>('taro-aweme-data-core', undefined, undefined, defineTaroAwemeDataCore);
export const TaroBlockCore = /*@__PURE__*/createReactComponent<JSX.TaroBlockCore, HTMLTaroBlockCoreElement>('taro-block-core', undefined, undefined, defineTaroBlockCore);
export const TaroButtonCore = /*@__PURE__*/createReactComponent<JSX.TaroButtonCore, HTMLTaroButtonCoreElement>('taro-button-core', undefined, undefined, defineTaroButtonCore);
export const TaroCameraCore = /*@__PURE__*/createReactComponent<JSX.TaroCameraCore, HTMLTaroCameraCoreElement>('taro-camera-core', undefined, undefined, defineTaroCameraCore);
export const TaroCanvasCore = /*@__PURE__*/createReactComponent<JSX.TaroCanvasCore, HTMLTaroCanvasCoreElement>('taro-canvas-core', undefined, undefined, defineTaroCanvasCore);
export const TaroChannelLiveCore = /*@__PURE__*/createReactComponent<JSX.TaroChannelLiveCore, HTMLTaroChannelLiveCoreElement>('taro-channel-live-core', undefined, undefined, defineTaroChannelLiveCore);
export const TaroChannelVideoCore = /*@__PURE__*/createReactComponent<JSX.TaroChannelVideoCore, HTMLTaroChannelVideoCoreElement>('taro-channel-video-core', undefined, undefined, defineTaroChannelVideoCore);
export const TaroCheckboxCore = /*@__PURE__*/createReactComponent<JSX.TaroCheckboxCore, HTMLTaroCheckboxCoreElement>('taro-checkbox-core', undefined, undefined, defineTaroCheckboxCore);
export const TaroCheckboxGroupCore = /*@__PURE__*/createReactComponent<JSX.TaroCheckboxGroupCore, HTMLTaroCheckboxGroupCoreElement>('taro-checkbox-group-core', undefined, undefined, defineTaroCheckboxGroupCore);
export const TaroCommentDetailCore = /*@__PURE__*/createReactComponent<JSX.TaroCommentDetailCore, HTMLTaroCommentDetailCoreElement>('taro-comment-detail-core', undefined, undefined, defineTaroCommentDetailCore);
export const TaroCommentListCore = /*@__PURE__*/createReactComponent<JSX.TaroCommentListCore, HTMLTaroCommentListCoreElement>('taro-comment-list-core', undefined, undefined, defineTaroCommentListCore);
export const TaroContactButtonCore = /*@__PURE__*/createReactComponent<JSX.TaroContactButtonCore, HTMLTaroContactButtonCoreElement>('taro-contact-button-core', undefined, undefined, defineTaroContactButtonCore);
export const TaroCoverImageCore = /*@__PURE__*/createReactComponent<JSX.TaroCoverImageCore, HTMLTaroCoverImageCoreElement>('taro-cover-image-core', undefined, undefined, defineTaroCoverImageCore);
export const TaroCoverViewCore = /*@__PURE__*/createReactComponent<JSX.TaroCoverViewCore, HTMLTaroCoverViewCoreElement>('taro-cover-view-core', undefined, undefined, defineTaroCoverViewCore);
export const TaroCustomWrapperCore = /*@__PURE__*/createReactComponent<JSX.TaroCustomWrapperCore, HTMLTaroCustomWrapperCoreElement>('taro-custom-wrapper-core', undefined, undefined, defineTaroCustomWrapperCore);
export const TaroDoubleTapGestureHandlerCore = /*@__PURE__*/createReactComponent<JSX.TaroDoubleTapGestureHandlerCore, HTMLTaroDoubleTapGestureHandlerCoreElement>('taro-double-tap-gesture-handler-core', undefined, undefined, defineTaroDoubleTapGestureHandlerCore);
export const TaroDraggableSheetCore = /*@__PURE__*/createReactComponent<JSX.TaroDraggableSheetCore, HTMLTaroDraggableSheetCoreElement>('taro-draggable-sheet-core', undefined, undefined, defineTaroDraggableSheetCore);
export const TaroEditorCore = /*@__PURE__*/createReactComponent<JSX.TaroEditorCore, HTMLTaroEditorCoreElement>('taro-editor-core', undefined, undefined, defineTaroEditorCore);
export const TaroFollowSwanCore = /*@__PURE__*/createReactComponent<JSX.TaroFollowSwanCore, HTMLTaroFollowSwanCoreElement>('taro-follow-swan-core', undefined, undefined, defineTaroFollowSwanCore);
export const TaroForcePressGestureHandlerCore = /*@__PURE__*/createReactComponent<JSX.TaroForcePressGestureHandlerCore, HTMLTaroForcePressGestureHandlerCoreElement>('taro-force-press-gesture-handler-core', undefined, undefined, defineTaroForcePressGestureHandlerCore);
export const TaroFormCore = /*@__PURE__*/createReactComponent<JSX.TaroFormCore, HTMLTaroFormCoreElement>('taro-form-core', undefined, undefined, defineTaroFormCore);
export const TaroFunctionalPageNavigatorCore = /*@__PURE__*/createReactComponent<JSX.TaroFunctionalPageNavigatorCore, HTMLTaroFunctionalPageNavigatorCoreElement>('taro-functional-page-navigator-core', undefined, undefined, defineTaroFunctionalPageNavigatorCore);
export const TaroGridBuilderCore = /*@__PURE__*/createReactComponent<JSX.TaroGridBuilderCore, HTMLTaroGridBuilderCoreElement>('taro-grid-builder-core', undefined, undefined, defineTaroGridBuilderCore);
export const TaroGridViewCore = /*@__PURE__*/createReactComponent<JSX.TaroGridViewCore, HTMLTaroGridViewCoreElement>('taro-grid-view-core', undefined, undefined, defineTaroGridViewCore);
export const TaroHorizontalDragGestureHandlerCore = /*@__PURE__*/createReactComponent<JSX.TaroHorizontalDragGestureHandlerCore, HTMLTaroHorizontalDragGestureHandlerCoreElement>('taro-horizontal-drag-gesture-handler-core', undefined, undefined, defineTaroHorizontalDragGestureHandlerCore);
export const TaroIconCore = /*@__PURE__*/createReactComponent<JSX.TaroIconCore, HTMLTaroIconCoreElement>('taro-icon-core', undefined, undefined, defineTaroIconCore);
export const TaroImageCore = /*@__PURE__*/createReactComponent<JSX.TaroImageCore, HTMLTaroImageCoreElement>('taro-image-core', undefined, undefined, defineTaroImageCore);
export const TaroInlinePaymentPanelCore = /*@__PURE__*/createReactComponent<JSX.TaroInlinePaymentPanelCore, HTMLTaroInlinePaymentPanelCoreElement>('taro-inline-payment-panel-core', undefined, undefined, defineTaroInlinePaymentPanelCore);
export const TaroInputCore = /*@__PURE__*/createReactComponent<JSX.TaroInputCore, HTMLTaroInputCoreElement>('taro-input-core', undefined, undefined, defineTaroInputCore);
export const TaroKeyboardAccessoryCore = /*@__PURE__*/createReactComponent<JSX.TaroKeyboardAccessoryCore, HTMLTaroKeyboardAccessoryCoreElement>('taro-keyboard-accessory-core', undefined, undefined, defineTaroKeyboardAccessoryCore);
export const TaroLabelCore = /*@__PURE__*/createReactComponent<JSX.TaroLabelCore, HTMLTaroLabelCoreElement>('taro-label-core', undefined, undefined, defineTaroLabelCore);
export const TaroLifestyleCore = /*@__PURE__*/createReactComponent<JSX.TaroLifestyleCore, HTMLTaroLifestyleCoreElement>('taro-lifestyle-core', undefined, undefined, defineTaroLifestyleCore);
export const TaroLikeCore = /*@__PURE__*/createReactComponent<JSX.TaroLikeCore, HTMLTaroLikeCoreElement>('taro-like-core', undefined, undefined, defineTaroLikeCore);
export const TaroListBuilderCore = /*@__PURE__*/createReactComponent<JSX.TaroListBuilderCore, HTMLTaroListBuilderCoreElement>('taro-list-builder-core', undefined, undefined, defineTaroListBuilderCore);
export const TaroListViewCore = /*@__PURE__*/createReactComponent<JSX.TaroListViewCore, HTMLTaroListViewCoreElement>('taro-list-view-core', undefined, undefined, defineTaroListViewCore);
export const TaroLivePlayerCore = /*@__PURE__*/createReactComponent<JSX.TaroLivePlayerCore, HTMLTaroLivePlayerCoreElement>('taro-live-player-core', undefined, undefined, defineTaroLivePlayerCore);
export const TaroLivePusherCore = /*@__PURE__*/createReactComponent<JSX.TaroLivePusherCore, HTMLTaroLivePusherCoreElement>('taro-live-pusher-core', undefined, undefined, defineTaroLivePusherCore);
export const TaroLoginCore = /*@__PURE__*/createReactComponent<JSX.TaroLoginCore, HTMLTaroLoginCoreElement>('taro-login-core', undefined, undefined, defineTaroLoginCore);
export const TaroLongPressGestureHandlerCore = /*@__PURE__*/createReactComponent<JSX.TaroLongPressGestureHandlerCore, HTMLTaroLongPressGestureHandlerCoreElement>('taro-long-press-gesture-handler-core', undefined, undefined, defineTaroLongPressGestureHandlerCore);
export const TaroLottieCore = /*@__PURE__*/createReactComponent<JSX.TaroLottieCore, HTMLTaroLottieCoreElement>('taro-lottie-core', undefined, undefined, defineTaroLottieCore);
export const TaroMapCore = /*@__PURE__*/createReactComponent<JSX.TaroMapCore, HTMLTaroMapCoreElement>('taro-map-core', undefined, undefined, defineTaroMapCore);
export const TaroMatchMediaCore = /*@__PURE__*/createReactComponent<JSX.TaroMatchMediaCore, HTMLTaroMatchMediaCoreElement>('taro-match-media-core', undefined, undefined, defineTaroMatchMediaCore);
export const TaroMovableAreaCore = /*@__PURE__*/createReactComponent<JSX.TaroMovableAreaCore, HTMLTaroMovableAreaCoreElement>('taro-movable-area-core', undefined, undefined, defineTaroMovableAreaCore);
export const TaroMovableViewCore = /*@__PURE__*/createReactComponent<JSX.TaroMovableViewCore, HTMLTaroMovableViewCoreElement>('taro-movable-view-core', undefined, undefined, defineTaroMovableViewCore);
export const TaroNativeSlotCore = /*@__PURE__*/createReactComponent<JSX.TaroNativeSlotCore, HTMLTaroNativeSlotCoreElement>('taro-native-slot-core', undefined, undefined, defineTaroNativeSlotCore);
export const TaroNavigationBarCore = /*@__PURE__*/createReactComponent<JSX.TaroNavigationBarCore, HTMLTaroNavigationBarCoreElement>('taro-navigation-bar-core', undefined, undefined, defineTaroNavigationBarCore);
export const TaroNavigatorCore = /*@__PURE__*/createReactComponent<JSX.TaroNavigatorCore, HTMLTaroNavigatorCoreElement>('taro-navigator-core', undefined, undefined, defineTaroNavigatorCore);
export const TaroNestedScrollBodyCore = /*@__PURE__*/createReactComponent<JSX.TaroNestedScrollBodyCore, HTMLTaroNestedScrollBodyCoreElement>('taro-nested-scroll-body-core', undefined, undefined, defineTaroNestedScrollBodyCore);
export const TaroNestedScrollHeaderCore = /*@__PURE__*/createReactComponent<JSX.TaroNestedScrollHeaderCore, HTMLTaroNestedScrollHeaderCoreElement>('taro-nested-scroll-header-core', undefined, undefined, defineTaroNestedScrollHeaderCore);
export const TaroOfficialAccountCore = /*@__PURE__*/createReactComponent<JSX.TaroOfficialAccountCore, HTMLTaroOfficialAccountCoreElement>('taro-official-account-core', undefined, undefined, defineTaroOfficialAccountCore);
export const TaroOpenContainerCore = /*@__PURE__*/createReactComponent<JSX.TaroOpenContainerCore, HTMLTaroOpenContainerCoreElement>('taro-open-container-core', undefined, undefined, defineTaroOpenContainerCore);
export const TaroOpenDataCore = /*@__PURE__*/createReactComponent<JSX.TaroOpenDataCore, HTMLTaroOpenDataCoreElement>('taro-open-data-core', undefined, undefined, defineTaroOpenDataCore);
export const TaroOpenEmbeddedAtomicserviceCore = /*@__PURE__*/createReactComponent<JSX.TaroOpenEmbeddedAtomicserviceCore, HTMLTaroOpenEmbeddedAtomicserviceCoreElement>('taro-open-embedded-atomicservice-core', undefined, undefined, defineTaroOpenEmbeddedAtomicserviceCore);
export const TaroPageContainerCore = /*@__PURE__*/createReactComponent<JSX.TaroPageContainerCore, HTMLTaroPageContainerCoreElement>('taro-page-container-core', undefined, undefined, defineTaroPageContainerCore);
export const TaroPageMetaCore = /*@__PURE__*/createReactComponent<JSX.TaroPageMetaCore, HTMLTaroPageMetaCoreElement>('taro-page-meta-core', undefined, undefined, defineTaroPageMetaCore);
export const TaroPanGestureHandlerCore = /*@__PURE__*/createReactComponent<JSX.TaroPanGestureHandlerCore, HTMLTaroPanGestureHandlerCoreElement>('taro-pan-gesture-handler-core', undefined, undefined, defineTaroPanGestureHandlerCore);
export const TaroPickerCore = /*@__PURE__*/createReactComponent<JSX.TaroPickerCore, HTMLTaroPickerCoreElement>('taro-picker-core', undefined, undefined, defineTaroPickerCore);
export const TaroPickerGroup = /*@__PURE__*/createReactComponent<JSX.TaroPickerGroup, HTMLTaroPickerGroupElement>('taro-picker-group', undefined, undefined, defineTaroPickerGroup);
export const TaroPickerViewColumnCore = /*@__PURE__*/createReactComponent<JSX.TaroPickerViewColumnCore, HTMLTaroPickerViewColumnCoreElement>('taro-picker-view-column-core', undefined, undefined, defineTaroPickerViewColumnCore);
export const TaroPickerViewCore = /*@__PURE__*/createReactComponent<JSX.TaroPickerViewCore, HTMLTaroPickerViewCoreElement>('taro-picker-view-core', undefined, undefined, defineTaroPickerViewCore);
export const TaroProgressCore = /*@__PURE__*/createReactComponent<JSX.TaroProgressCore, HTMLTaroProgressCoreElement>('taro-progress-core', undefined, undefined, defineTaroProgressCore);
export const TaroPullToRefreshCore = /*@__PURE__*/createReactComponent<JSX.TaroPullToRefreshCore, HTMLTaroPullToRefreshCoreElement>('taro-pull-to-refresh-core', undefined, undefined, defineTaroPullToRefreshCore);
export const TaroRadioCore = /*@__PURE__*/createReactComponent<JSX.TaroRadioCore, HTMLTaroRadioCoreElement>('taro-radio-core', undefined, undefined, defineTaroRadioCore);
export const TaroRadioGroupCore = /*@__PURE__*/createReactComponent<JSX.TaroRadioGroupCore, HTMLTaroRadioGroupCoreElement>('taro-radio-group-core', undefined, undefined, defineTaroRadioGroupCore);
export const TaroRichTextCore = /*@__PURE__*/createReactComponent<JSX.TaroRichTextCore, HTMLTaroRichTextCoreElement>('taro-rich-text-core', undefined, undefined, defineTaroRichTextCore);
export const TaroRootPortalCore = /*@__PURE__*/createReactComponent<JSX.TaroRootPortalCore, HTMLTaroRootPortalCoreElement>('taro-root-portal-core', undefined, undefined, defineTaroRootPortalCore);
export const TaroRtcRoomCore = /*@__PURE__*/createReactComponent<JSX.TaroRtcRoomCore, HTMLTaroRtcRoomCoreElement>('taro-rtc-room-core', undefined, undefined, defineTaroRtcRoomCore);
export const TaroRtcRoomItemCore = /*@__PURE__*/createReactComponent<JSX.TaroRtcRoomItemCore, HTMLTaroRtcRoomItemCoreElement>('taro-rtc-room-item-core', undefined, undefined, defineTaroRtcRoomItemCore);
export const TaroScaleGestureHandlerCore = /*@__PURE__*/createReactComponent<JSX.TaroScaleGestureHandlerCore, HTMLTaroScaleGestureHandlerCoreElement>('taro-scale-gesture-handler-core', undefined, undefined, defineTaroScaleGestureHandlerCore);
export const TaroScriptCore = /*@__PURE__*/createReactComponent<JSX.TaroScriptCore, HTMLTaroScriptCoreElement>('taro-script-core', undefined, undefined, defineTaroScriptCore);
export const TaroScrollViewCore = /*@__PURE__*/createReactComponent<JSX.TaroScrollViewCore, HTMLTaroScrollViewCoreElement>('taro-scroll-view-core', undefined, undefined, defineTaroScrollViewCore);
export const TaroShareElementCore = /*@__PURE__*/createReactComponent<JSX.TaroShareElementCore, HTMLTaroShareElementCoreElement>('taro-share-element-core', undefined, undefined, defineTaroShareElementCore);
export const TaroSliderCore = /*@__PURE__*/createReactComponent<JSX.TaroSliderCore, HTMLTaroSliderCoreElement>('taro-slider-core', undefined, undefined, defineTaroSliderCore);
export const TaroSlotCore = /*@__PURE__*/createReactComponent<JSX.TaroSlotCore, HTMLTaroSlotCoreElement>('taro-slot-core', undefined, undefined, defineTaroSlotCore);
export const TaroSnapshotCore = /*@__PURE__*/createReactComponent<JSX.TaroSnapshotCore, HTMLTaroSnapshotCoreElement>('taro-snapshot-core', undefined, undefined, defineTaroSnapshotCore);
export const TaroSpanCore = /*@__PURE__*/createReactComponent<JSX.TaroSpanCore, HTMLTaroSpanCoreElement>('taro-span-core', undefined, undefined, defineTaroSpanCore);
export const TaroStickyHeaderCore = /*@__PURE__*/createReactComponent<JSX.TaroStickyHeaderCore, HTMLTaroStickyHeaderCoreElement>('taro-sticky-header-core', undefined, undefined, defineTaroStickyHeaderCore);
export const TaroStickySectionCore = /*@__PURE__*/createReactComponent<JSX.TaroStickySectionCore, HTMLTaroStickySectionCoreElement>('taro-sticky-section-core', undefined, undefined, defineTaroStickySectionCore);
export const TaroSwiperCore = /*@__PURE__*/createReactComponent<JSX.TaroSwiperCore, HTMLTaroSwiperCoreElement>('taro-swiper-core', undefined, undefined, defineTaroSwiperCore);
export const TaroSwiperItemCore = /*@__PURE__*/createReactComponent<JSX.TaroSwiperItemCore, HTMLTaroSwiperItemCoreElement>('taro-swiper-item-core', undefined, undefined, defineTaroSwiperItemCore);
export const TaroSwitchCore = /*@__PURE__*/createReactComponent<JSX.TaroSwitchCore, HTMLTaroSwitchCoreElement>('taro-switch-core', undefined, undefined, defineTaroSwitchCore);
export const TaroTabItemCore = /*@__PURE__*/createReactComponent<JSX.TaroTabItemCore, HTMLTaroTabItemCoreElement>('taro-tab-item-core', undefined, undefined, defineTaroTabItemCore);
export const TaroTabbar = /*@__PURE__*/createReactComponent<JSX.TaroTabbar, HTMLTaroTabbarElement>('taro-tabbar', undefined, undefined, defineTaroTabbar);
export const TaroTabsCore = /*@__PURE__*/createReactComponent<JSX.TaroTabsCore, HTMLTaroTabsCoreElement>('taro-tabs-core', undefined, undefined, defineTaroTabsCore);
export const TaroTapGestureHandlerCore = /*@__PURE__*/createReactComponent<JSX.TaroTapGestureHandlerCore, HTMLTaroTapGestureHandlerCoreElement>('taro-tap-gesture-handler-core', undefined, undefined, defineTaroTapGestureHandlerCore);
export const TaroTextCore = /*@__PURE__*/createReactComponent<JSX.TaroTextCore, HTMLTaroTextCoreElement>('taro-text-core', undefined, undefined, defineTaroTextCore);
export const TaroTextareaCore = /*@__PURE__*/createReactComponent<JSX.TaroTextareaCore, HTMLTaroTextareaCoreElement>('taro-textarea-core', undefined, undefined, defineTaroTextareaCore);
export const TaroVerticalDragGestureHandlerCore = /*@__PURE__*/createReactComponent<JSX.TaroVerticalDragGestureHandlerCore, HTMLTaroVerticalDragGestureHandlerCoreElement>('taro-vertical-drag-gesture-handler-core', undefined, undefined, defineTaroVerticalDragGestureHandlerCore);
export const TaroVideoControl = /*@__PURE__*/createReactComponent<JSX.TaroVideoControl, HTMLTaroVideoControlElement>('taro-video-control', undefined, undefined, defineTaroVideoControl);
export const TaroVideoCore = /*@__PURE__*/createReactComponent<JSX.TaroVideoCore, HTMLTaroVideoCoreElement>('taro-video-core', undefined, undefined, defineTaroVideoCore);
export const TaroVideoDanmu = /*@__PURE__*/createReactComponent<JSX.TaroVideoDanmu, HTMLTaroVideoDanmuElement>('taro-video-danmu', undefined, undefined, defineTaroVideoDanmu);
export const TaroViewCore = /*@__PURE__*/createReactComponent<JSX.TaroViewCore, HTMLTaroViewCoreElement>('taro-view-core', undefined, undefined, defineTaroViewCore);
export const TaroVoipRoomCore = /*@__PURE__*/createReactComponent<JSX.TaroVoipRoomCore, HTMLTaroVoipRoomCoreElement>('taro-voip-room-core', undefined, undefined, defineTaroVoipRoomCore);
export const TaroWebViewCore = /*@__PURE__*/createReactComponent<JSX.TaroWebViewCore, HTMLTaroWebViewCoreElement>('taro-web-view-core', undefined, undefined, defineTaroWebViewCore);
